apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: udmsim
  name: udmsim
  namespace: actimize
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: udmsim
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: udmsim
      namespace: actimize
    spec:
      containers:
      - env:
        - name: AWS_ROLE_ARN
          value: arn:aws:iam::556277294023:role/actimize-prod-k8s-pods
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /run/secrets/eks.amazonaws.com/serviceaccount/token
        - name: SQS_QUEUE_ENDPOINT
          value: https://sqs.us-east-1.amazonaws.com/556277294023/robinhood-actimize-log-sink-dev
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: AWS_REGION
          value: us-east-1
        - name: LOG
          value: info
        - name: VECTOR_SELF_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: VECTOR_SELF_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: VECTOR_SELF_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: timberio/vector:0.21.2-debian
        imagePullPolicy: IfNotPresent
        name: vector-sidecar
        ports:
        - containerPort: 9090
          name: metrics
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/actimize/udmsim
          name: data
        - mountPath: /opt/actimize/ais_server/Instances/udmsim/logs
          name: logs
        - mountPath: /var/log/
          name: var-log
          readOnly: true
        - mountPath: /var/lib
          name: var-lib
          readOnly: true
        - mountPath: /vector-data-dir
          name: data-dir
        - mountPath: /etc/vector
          name: config-dir
          readOnly: true
        - mountPath: /host/proc
          name: procfs
          readOnly: true
        - mountPath: /host/sys
          name: sysfs
          readOnly: true
      dnsPolicy: ClusterFirst
      hostname: udmsim
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: actimize-prod-k8s-pods
      serviceAccountName: actimize-prod-k8s-pods
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: udmsim
      - name: logs
        persistentVolumeClaim:
          claimName: udmsim-logs
      - hostPath:
          path: /var/log/
          type: ""
        name: var-log
      - hostPath:
          path: /var/lib/
          type: ""
        name: var-lib
      - hostPath:
          path: /var/lib/vector/
          type: ""
        name: data-dir
      - hostPath:
          path: /proc/
          type: ""
        name: procfs
      - hostPath:
          path: /sys/
          type: ""
        name: sysfs
      - name: config-dir
        projected:
          defaultMode: 420
          sources:
          - configMap:
              name: udmsim-vector-sidecar
