apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  generation: 5
  labels:
    app: efiler
    app.kubernetes.io/managed-by: CodeBuild
  name: efiler
  namespace: actimize
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: efiler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: efiler
      namespace: actimize
    spec:
      containers:
      - env:
        - name: AWS_ROLE_ARN
          value: arn:aws:iam::556277294023:role/actimize-test-k8s-pods
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /run/secrets/eks.amazonaws.com/serviceaccount/token
        image: apache:apache
        imagePullPolicy: Always
        name: efiler
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/actone/working_dir/outgoingForms
          name: rcm-sars
        - mountPath: /opt/EfileTool/log
          name: logs
        - mountPath: /opt/EfileTool/logFolder_IS_UNDEFINED
          name: logs-undefined
        - mountPath: /var/log
          name: app-var-log
